using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("VisualCoverage")]
[assembly: AssemblyDescriptionAttribute("A Tool to create a clover report from Visual Studio Coverage files.")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2012-2023 Joaquin Sargiotto")]
[assembly: AssemblyVersionAttribute("1.0.0.3")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.3")]

