using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProductAttribute("VisualCoverage")]
[assembly: AssemblyDescriptionAttribute("A Tool to create a clover report from Visual Studio Coverage files.")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2012-2023 Joaquin Sargiotto")]
[assembly: AssemblyVersionAttribute("1.0.0.3")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.3")]

